# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d01f918913ae1bd01f3665580730e1f8908e213397f9864d9e076492c232cb62c91843fe61303a82e8ce9b3009031d0eb3e498f843cadf5560be7e32184fb0e

test:
  secret_key_base: 5dcc00fdfcd59a1eea49e769d4a9bcb924b48fe98f42945d681bc9dbc4f8ef52e59e7ff4dc80c84abc3e3ee79d5991d3b2b9d48f8965356cc0988bc0ca4013b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
